project:
  type: website

website:
  title: "PTR5932"
  sidebar:
    style: "docked" # Options: "docked" or "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Aula 01"
        href: aula01.qmd
      - text: "Referências"
        href: referencias.qmd
      - section: "More Info"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



